name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: oguzhnatly
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Lisbon
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_details: lines, percentage
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_ignored: tex, less, makefile, qmake, lex, cmake, gnuplot, scala, c, c++, ejs, blade, hack
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_sections: base
          plugin_releases: yes
          plugin_releases_limit: 1
          plugin_repositories: yes
          plugin_repositories_starred: 1